# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service.proto", :syntax => :proto3) do
    add_message "xyzzy.PingRequest" do
    end
    add_message "xyzzy.PingOk" do
    end
  end
end

module Xyzzy
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xyzzy.PingRequest").msgclass
  PingOk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xyzzy.PingOk").msgclass
end
