// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
import {xyzzy} from './service.pb';
import {createTwirpAdapter} from 'pbjs-twirp';
import Axios from 'axios';

const getServiceMethodName = (fn: any): string => {
	if (fn === xyzzy.XyzzyData.prototype.ping) {
		return 'Ping';
    }

    throw new Error('Unknown Method');
};


export const XyzzyDataPathPrefix = '/twirp/xyzzy.XyzzyData/';

export const createXyzzyData = (baseURL: string, options = {}): xyzzy.XyzzyData => {
    const defaultOpts = {
        baseURL: baseURL + XyzzyDataPathPrefix,
        headers: {
          Accept: 'application/protobuf'
        }
    };
    const axiosOpts = { ...defaultOpts, ...options };
    
    const axios = Axios.create(axiosOpts);

    return xyzzy.XyzzyData.create(createTwirpAdapter(axios, getServiceMethodName));
};
